### ISSUE TITLE
Implement serializable?

### ISSUE THREAD

**Issue by dtubenetwork** [multiformats/java-multihash#22]
Would it be possible to implement serializable?

**Comment by ianopolous** [comment]
In principle yes, but I'd like hear more about the usecase first.

**Comment by dtubenetwork** [comment]
Storing multihash(s) in database (hashmap, mapdb).

**Comment by ianopolous** [comment]
Ok If you're not super space sensitive, I'd use the toString() == base58()
If you want a minimal binary representation then use toBytes()

But probably you want to be using Cid rather than multihash?

**Comment by dtubenetwork** [comment]
I forgot to mention the multihash is part of an object that gets serialized into the database. I currently have a Gson.toJson of that object for serialization into mapdb. 

What is the different between multihash and Cid? Thanks

**Comment by ianopolous** [comment]
Cid has some extra information about the object it points to, specifically the encoding of the data (cbor, raw etc) Where do you originally get the Multihashes from? Note that Cid extends Multihash.

**Comment by ianopolous** [comment]
A potential issue with adding serializable here is that it may not play well with Cids. Which is why I ask how you're getting the multihashes.

**Comment by dtubenetwork** [comment]
The Multihash's are obtained by base58 decoding `Multihash.fromBase58` the hash (Qm, unixFS, Cidv0) string from JSON Doesn't when you implement Serializable you can change/override the `serialVersionUID` so they won't conflict?

**Comment by ianopolous** [comment]
Ok but where are you getting the hash, i.e. what api call? Some return raw multihashes, but some normally return Cids.

**Comment by dtubenetwork** [comment]
No API call, base58 string from external source. Which is decoded into multihash.

**Comment by ianopolous** [comment]
Ok. Certainly if you're storing it as json in mapdb you should be fine with the base58() encoding to a string.

**Comment by dtubenetwork** [comment]
Mapdb has the ability to write a custom serializer. I created one for the object where i am storing the multihash(s) in (VideoEntry). The custom serializer converts my object into json bytes which mapdb uses to store in its data file. [VideoEntry.java](https://gitlab.com/vaultec/permanente/blob/dev-01/Permanente/src/io/permanente/primitives/VideoEntry.java) [VideoEntry serializer](https://gitlab.com/vaultec/permanente/blob/dev-01/Permanente/src/io/permanente/primitives/Serializers.java#L19).. I am not entirely sure but when i was first writing this i got issues (serializableException) with serializing multihash. After adding serializable to Multihash.java it fixed the issue.
